### ISSUE TITLE
Should we implement `buy` functions?

### ISSUE THREAD

**Issue by albertocuestacanada** [alexroan/USM#37]
I'm noticing, though, that all the `buy` functions are missing from the system. We can use a precise amount of ETH to `fund` for an unknown amount of FUM. What if the user wants to mint exactly 1 FUM?

Same with all others. Would we just reverse the logic in the frontend? Code it in the smart contracts? Not implement it?

**Comment by alexroan** [comment]
The UI can use `ethToUsm` and `usmToEth` (and/or `fumPrice`) to calculate this on the fly. 

For mint and burn this will be super easy client-side call. A little more complicated for Fum, but negligible to be honest. I don't think it warrants the extra solidity functions.

**Comment by jacob-eliosoff** [comment]
Well, no, with sliding prices it's not quite so simple: the ETH/USM and ETH/FUM conversion rates are nonlinear (ie, depend on the trade size, like in Uniswap).

But, the math is really not so bad.  I'd be inclined to leave it to UIs to duplicate.

If we did decide to add functions where the user specifies output rather than input, I don't foresee any problems.  Very analogous to existing fns.  Just increases our code size, tests, audit cost etc.

It's worth noting though that there _are_ behavior differences:
a) If I tell `mint()` "Here's 1 ETH, give me some USM", my worst case is the ETH price plummets before my request is executed and I end up receiving ~0 USM.
b) Whereas if I tell `mint()` "I need 300 USM, charge me some ETH", my worst case is the ETH price plummets and I'm charged a huge amount of ETH.  A lot worse than (a)!  Right?

**Comment by albertocuestacanada** [comment]
That's why you have limit orders (same as Uniswap). You would say "I want 300 USM, but only if that would be less than 1.5 ETH".

As discussed elsewhere, let's park this and keep minimalist. If we need it (as a feature or for the UI) let's build it. Let's not do it just because we can.

**Comment by jacob-eliosoff** [comment]
"If we need it let's build it.  Let's not do it just because we can" - yeah exactly.  The only cases where I'm inclined to bend this rule of thumb are if a feature significantly improves/incentivizes the safety of the system.  Eg:
- I added sliding prices, even though they significantly increase complexity, because I really think without them the system is very vulnerable to price arbitrage.  (I basically think _any_ system where buying doesn't push up the buy price is broken.)
- There's a similar (though weaker) case for proper resting limit orders, where a user can leave some ETH (or better yet USM) to buy FUM if the FUM price drops.  I think such orders may be the single feature that would most reduce the likelihood of going underwater.  Seems like a _lot_ of extra complexity though (trees etc - a lot more than sliding prices), so not right now.

But yeah in general "When there's a real need, not just when it seems nice" is a good rule for this project.
